### ISSUE TITLE
Parser Anzahl Personen defekt!

### ISSUE THREAD

**Issue by Promichel** [Promichel/Rezeptkram#4]
Rezept: http://www.chefkoch.de/rezepte/1729881282114564/Roastbeef.html
Exception: java.lang.NumberFormatException: For input string: "&#189;"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
    at java.lang.Integer.parseInt(Integer.java:449)
    at java.lang.Integer.parseInt(Integer.java:499)
    at de.schulprojekt.parsers.chefkoch.ChefkochParser.getFloatFromQuantity(ChefkochParser.java:144)

Flott fixen pls :) Da hast du wohl noch nen Fehler in deiner RegEx. bzw. bau bitte nen Check ein und werf ne ParserException wenn es nicht klappt

**Comment by Promichel** [comment]
Das gleiche gilt auch noch für die Titel. Du kannst mir die in der Entity Bean ruhig ohne HTML COnverting zurückgeben

**Comment by 11111000101** [comment]
ok
wird erledigt
